INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Paracetamol 500mg', 'Analgesico y antipirético en tabletas', 32.50, 120, '2027-05-10');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Ibuprofeno 400mg', 'Antiinflamatorio no esteroideo en tabletas', 48.00, 90, '2026-11-22');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Amoxicilina 500mg', 'Antibiótico de amplio espectro en cápsulas', 85.00, 60, '2026-03-18');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Omeprazol 20mg', 'Inhibidor de bomba de protones en cápsulas', 55.00, 75, '2027-01-05');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Loratadina 10mg', 'Antihistamínico para alergias', 29.90, 150, '2026-09-12');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Metformina 850mg', 'Fármaco para control de glucosa', 62.00, 110, '2027-02-20');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Diclofenaco 50mg', 'Antiinflamatorio y analgésico', 37.00, 140, '2026-07-30');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Losartan 50mg', 'Antihipertensivo en tabletas', 74.50, 80, '2027-03-11');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Salbutamol Inhalador', 'Broncodilatador en aerosol', 120.00, 45, '2026-12-01');
INSERT INTO productos (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Ácido Fólico 5mg', 'Suplemento vitamínico en tabletas', 26.00, 200, '2027-04-25');
