INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Yogur Natural', 'Yogur natural sin azúcar, presentación de 250g', 18.50, 40, '2026-02-10');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Pan Integral', 'Pan integral de caja 600g', 32.00, 25, '2025-12-05');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Leche Deslactosada', 'Litro de leche deslactosada baja en grasa', 27.90, 50, '2026-01-15');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Cereal de Avena', 'Cereal de avena con miel 300g', 45.00, 15, '2026-03-20');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Jugo de Naranja', 'Jugo natural pasteurizado 1L', 22.00, 30, '2025-11-30');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Galletas Integrales', 'Paquete de galletas integrales 200g', 16.50, 60, '2026-04-18');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Pasta Spaghetti', 'Pasta tipo spaghetti 500g', 14.00, 80, '2027-01-01');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Arroz Blanco', 'Bolsa de arroz blanco 1kg', 21.00, 70, '2027-03-05');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Atún en Agua', 'Lata de atún en agua 140g', 19.50, 100, '2027-06-10');
INSERT INTO producto (nombre, descripcion, precio, stock, fecha_caducidad) VALUES ('Aceite de Oliva', 'Botella de aceite de oliva extra virgen 500ml', 98.00, 20, '2026-12-22');
